apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vteam-ambient-runner

# Namespace for all resources (can be overridden with kustomize edit set namespace)
#namespace: sallyom-vteam
namespace: ambient-code

# Resources to include in deployment
resources:
- namespace.yaml
- pvc.yaml
- workspace-pvc.yaml
- crd.yaml
- rbac.yaml
- secrets.yaml
- git-configmap.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- operator-deployment.yaml
- route.yaml
images:
- name: quay.io/ambient_code/vteam_backend:latest
  newName: quay.io/ambient_code/vteam_backend
  newTag: latest
- name: quay.io/ambient_code/vteam_claude_runner:latest
  newName: quay.io/ambient_code/vteam_claude_runner
  newTag: latest
- name: quay.io/ambient_code/vteam_frontend:latest
  newName: quay.io/ambient_code/vteam_frontend
  newTag: latest
- name: quay.io/ambient_code/vteam_operator:latest
  newName: quay.io/ambient_code/vteam_operator
  newTag: latest
