apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- operator-sa.yaml
- operator-clusterrole.yaml
- operator-clusterrolebinding.yaml
- backend-sa.yaml
- backend-clusterrole.yaml
- backend-clusterrolebinding.yaml
- ambient-project-admin-clusterrole.yaml
- ambient-project-edit-clusterrole.yaml
- ambient-project-view-clusterrole.yaml
- frontend-rbac.yaml
- aggregate-agenticsessions-admin.yaml
- aggregate-projectsettings-admin.yaml
- aggregate-rfeworkflows-admin.yaml


